nelmio_api_doc:
    documentation:
        info:
            title: Netatmo connect
            description: "Netatmo Connect, Netatmo's APIs suite, enables third party apps and services to interact with Netatmo products."
            version: 1.0.0
    areas: # to filter documented areas
        path_patterns:
            - ^/netatmo # Accepts routes under /netatmo
