dist: trusty
language: php
addons:
  sonarcloud:
    organization: vincent-besseau
    token:
      secure: Q5NMtRBa8DLitn8uw6y1soq3FlBFcFkF3aFDXzCLWy4q8KdmwKFswG88Y1DLxXzQw8kAQ3rz9BgrmcZgm4VASWjQ6SNa3zRequRzOk4wn5J9c9UlWWteK2AawHHChiuikeYIU0G3moPH8tTQ4PKpyNidjJd3MnKL0f8UYHTPBd6LsqnDlMphIo5/GddHUKmTMB76re+Hzpj0sKtZsWt5qtarEOs+P8kDJmHptE0S2Hd3F95h22DgogIdEDOr8nU9lPHZ5dIvHutXwS4tp8sbydZmGjuUXEv+dkqjRb5sLWJFFuueOf2/aJC5ryL5CnOihQASg/9o/uExJtErZcGXgyjnYE22dY+DtbXCoyOK74sgJPDFFLFhuYpXEkngzFGOuGqe9PURxvbBFB2cQN6DV/lYE3Gy4Tuj4T32bOUF0Tagg6pYdqokD3cJmlZUu1keGWetSgBaXGFdk0LlTM68gYHdl97dz6sNbHEWrFfqBeHbApiyXfXci8iulf9wU72AHrioFuXU1Z2e0Tc79DLzS5MqutXJw1qmiGoggA2RcaxogZPMo96VJAfCjRUtDynb1VTOY94RErfT6COgOMQL0r70Taf4EwKWlGHows5WD9amzkqCt7ECtXVzhgllCLUojkJ0y0xHleiVoJ6XQHXdPuNzDKyNH+yBW4etZPTRgOE=
script:
- sonar-scanner
